CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE IF NOT EXISTS "Aluno" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nome" VARCHAR(255) NOT NULL,
    "numero_phiz" VARCHAR(255),
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Serie" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ano_inicio" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Sala" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_serie" INTEGER NOT NULL,
    "ano" INTEGER NOT NULL,
    "letra" CHAR(1) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Aluno_Sala" (
    "id_aluno" INTEGER NOT NULL,
    "id_sala" INTEGER NOT NULL,
    "atual" BOOLEAN NOT NULL,
    PRIMARY KEY ("id_aluno", "id_sala")
);

CREATE TABLE IF NOT EXISTS "Materia" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nome" VARCHAR(255) NOT NULL,
    "tipo" VARCHAR(255),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Professor" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nome" VARCHAR(255) NOT NULL,
    "numero_phiz" VARCHAR(255),
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "ativo" BOOLEAN NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Sala_Materia" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_sala" INTEGER NOT NULL,
    "id_materia" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Professor_Sala_Materia" (
    "id_professor" INTEGER NOT NULL,
    "id_sala_materia" INTEGER NOT NULL,
    "ativo" BOOLEAN NOT NULL,
    PRIMARY KEY ("id_professor", "id_sala_materia")
);

CREATE TABLE IF NOT EXISTS "Avaliacao" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_sala_materia" INTEGER NOT NULL,
    "periodo" CHAR(1) NOT NULL,
    "nome" VARCHAR(255),
    "peso_nota" DECIMAL(4,2) NOT NULL DEFAULT 1.00,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Nota" (
    "id_aluno" INTEGER NOT NULL,
    "id_avaliacao" INTEGER NOT NULL,
    "valor" DECIMAL(5,2) NOT NULL,
    PRIMARY KEY ("id_aluno", "id_avaliacao")
);

CREATE TABLE IF NOT EXISTS "Fila_Notificacao" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email_destino" VARCHAR(255) NOT NULL,
    "conteudo" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Coordenador" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nome" VARCHAR(255) NOT NULL,
    "numero_phiz" VARCHAR(255),
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "ativo" BOOLEAN NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Coordenador_Serie" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_coordenador" INTEGER NOT NULL,
    "id_serie" INTEGER NOT NULL,
    "ativo" BOOLEAN NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Aula" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_sala_materia" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Presenca" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_aula" INTEGER NOT NULL,
    "id_aluno" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

-- ===========================
-- FOREIGN KEYS
-- ===========================

ALTER TABLE "Sala"
ADD CONSTRAINT "fk_sala_serie"
FOREIGN KEY ("id_serie")
REFERENCES "Serie" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Aluno_Sala"
ADD CONSTRAINT "fk_aluno_sala_aluno"
FOREIGN KEY ("id_aluno")
REFERENCES "Aluno" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Aluno_Sala"
ADD CONSTRAINT "fk_aluno_sala_sala"
FOREIGN KEY ("id_sala")
REFERENCES "Sala" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Sala_Materia"
ADD CONSTRAINT "fk_sala_materia_sala"
FOREIGN KEY ("id_sala")
REFERENCES "Sala" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Sala_Materia"
ADD CONSTRAINT "fk_sala_materia_materia"
FOREIGN KEY ("id_materia")
REFERENCES "Materia" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Professor_Sala_Materia"
ADD CONSTRAINT "fk_psm_professor"
FOREIGN KEY ("id_professor")
REFERENCES "Professor" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Professor_Sala_Materia"
ADD CONSTRAINT "fk_psm_sala_materia"
FOREIGN KEY ("id_sala_materia")
REFERENCES "Sala_Materia" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Avaliacao"
ADD CONSTRAINT "fk_avaliacao_sala_materia"
FOREIGN KEY ("id_sala_materia")
REFERENCES "Sala_Materia" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Nota"
ADD CONSTRAINT "fk_nota_aluno"
FOREIGN KEY ("id_aluno")
REFERENCES "Aluno" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Nota"
ADD CONSTRAINT "fk_nota_avaliacao"
FOREIGN KEY ("id_avaliacao")
REFERENCES "Avaliacao" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Coordenador_Serie"
ADD CONSTRAINT "fk_coord_serie_coord"
FOREIGN KEY ("id_coordenador")
REFERENCES "Coordenador" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Coordenador_Serie"
ADD CONSTRAINT "fk_coord_serie_serie"
FOREIGN KEY ("id_serie")
REFERENCES "Serie" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Aula"
ADD CONSTRAINT "fk_aula_sala_materia"
FOREIGN KEY ("id_sala_materia")
REFERENCES "Sala_Materia" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Presenca"
ADD CONSTRAINT "fk_presenca_aula"
FOREIGN KEY ("id_aula")
REFERENCES "Aula" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Presenca"
ADD CONSTRAINT "fk_presenca_aluno"
FOREIGN KEY ("id_aluno")
REFERENCES "Aluno" ("id")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Fila_Notificacao"
ADD CONSTRAINT "fk_notificacao_professor"
FOREIGN KEY ("email_destino")
REFERENCES "Professor" ("email")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE "Fila_Notificacao"
ADD CONSTRAINT "fk_notificacao_aluno"
FOREIGN KEY ("email_destino")
REFERENCES "Aluno" ("email")
ON UPDATE NO ACTION
ON DELETE NO ACTION;