-- ===========================
-- MIGRATION: Tabela de Tokens de Autenticação
-- Descrição: Armazena tokens seguros para o fluxo de autenticação
--            via email + celular para vincular numero_phiz ao Aluno.
-- ===========================

CREATE TABLE IF NOT EXISTS "Token_Autenticacao" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "token" VARCHAR(255) NOT NULL UNIQUE,
    "polling_token" VARCHAR(255) NOT NULL UNIQUE,
    "email" VARCHAR(255) NOT NULL,
    "numero_celular" VARCHAR(255) NOT NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    "expira_em" TIMESTAMP NOT NULL,
    "utilizado" BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);

-- Foreign key: email deve existir na tabela Aluno
ALTER TABLE "Token_Autenticacao"
ADD CONSTRAINT "fk_token_auth_aluno_email"
FOREIGN KEY ("email")
REFERENCES "Aluno" ("email")
ON UPDATE NO ACTION
ON DELETE NO ACTION;

-- Índice para buscas rápidas por token
CREATE INDEX IF NOT EXISTS "idx_token_autenticacao_token"
ON "Token_Autenticacao" ("token");
